# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:15.0.7
  amd64: ghcr.io/hassio-addons/base:15.0.7
  armv7: ghcr.io/hassio-addons/base:15.0.7
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: CoMon"
  org.opencontainers.image.description: "A simple tool for Condition Monitoring"
  org.opencontainers.image.source: "https://github.com/hchris1/Addon-CoMon"
  org.opencontainers.image.licenses: "MIT"
args:
  COMON_VERSION: "0.4.3"
