name: CoMon
version: "0.4.3"
slug: comon
description: A simple tool for Condition Monitoring
services:
  - "mqtt:want"
discovery:
  - "mqtt"
panel_icon: mdi:heart
url: https://github.com/hchris1/Addon-CoMon
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface
image: "ghcr.io/hchris1/{arch}-addon-comon"
ingress: true
schema:
  MqttEnabled: bool?
  OverrideMqttUsername: str?
  OverrideMqttPassword: str?
  OverrideMqttHost: str?
  OverrideMqttPort: int?
